###################################
#                                 #
#   E.A.R.L. Configuration File   #
#                                 #
###################################


# General settings for E.A.R.L.
# -----------------------------
# Base path for all E.A.R.L. links
# The value should begin with 'http', 'https' or '//'. If a bare URL is provided, '//' will be prepended.
_earl_base: 'http://cdn.example.org'


# Config groups for E.A.R.L.
# --------------------------
# JS helper group
_earl_path_js: 'path/to/js/files'
_earl_ext_js: '.js'

# CSS helper group
_earl_path_css: 'path/to/css/files'
_earl_ext_css: '.css'

# Image helper group
_earl_path_img: 'path/to/img/files'
# NEVER DEFINE _earl_ext_img